server:
  address: 127.0.0.1
  port: 7771

logging:
  config: ./buycycle/config/logback.xml

spring:
  application:
    name: buycycle

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone:

ebest:
  resRootPath: 'C:\\eBEST\\xingAPI\\Res'
  connect:
    szServerIP: 'hts.ebestsec.co.kr'
    nServerPort: 20001
    connectTimeOut: 5000
    requestReadTimeOut: 10000
  user:
    id: ''
    pw: ''
    cpwd: ''